### ISSUE TITLE
itemViews are called modelViews but collectionViews requre itemViews

### ISSUE THREAD

**Issue by amoskyler** [fissionjs/fission#52]
for consistency collectionView should probably take a modelView instead of an itemView

```javascript
var modelView = fission.modelView({
   model: Todo,
   render: function(){
     return Todo;
   }
});

var collectionView = fission.collectionView({
  model: Todo,
  itemView: modelView //for consistency should probably be modelView not itemView
)};
```

**Comment by contra** [comment]
I think this is cleared up, but we can revisit if you still think this is confusing. The term itemView is generally what is used when defining a collectionView but I'm open to renaming it
